name: Docker
on:
 release:
   branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: action/checkout@v4

     - name: Docker Hub auth
       uses: docker/login-action@v2
       witch:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secret.DOCKER_PASSWORD }}

     - name: Docker meta
       id: meta
       uses: docker/metadata-action@v4
       witch:
         images: orel2287/pogoda1
         tags: |
             type=schedule
             type=ref, event=pr
             type=semver, pattern={{version}}
     - name: Build and push Docker
       uses: docker/build-push-action@v4
       witch:
         context: .
         file: Dockerfile
         push: true
         tags: ${{ steps.meta.outputs.tags }}
         labels: ${{steps.meta.outputs.labels }}